New structure of dockerfiles

diff --git a/environment/dev-local/Dockerfile b/environment/dev-local/Dockerfile
--- a/environment/dev-local/Dockerfile
+++ b/environment/dev-local/Dockerfile
@@ -1,7 +1,4 @@
-FROM python:3.6.9-slim
-
-ARG ssh_prv_key
-ARG ssh_pub_key
+FROM xalperte/base-davinci:0.1
 
 # DB connection information
 ENV DB_USER tfm_uoc
@@ -23,58 +20,16 @@ ENV HAYSTACK_URL="http://host.docker.internal:8983/solr"
 # REDIS connection information
 ENV REDIS_HOST_PRIMARY tfm_uoc_redis
 
-# CHROMIUM configuration
-ENV CHROMIUM_BIN_FILE="/usr/bin/chromium"
-
-# Install all the dependencies
-RUN apt-get update && \
-    apt-get install -y \
-        git \
-        openssh-server \
-        libgdal-dev \
-        libev4 \
-        libev-dev \
-        build-essential \
-        curl \
-        unzip \
-        xvfb \
-        tinywm \
-        fonts-ipafont-gothic xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic \
-        chromium
-
-ENV CPLUS_INCLUDE_PATH /usr/include/gdal
-ENV C_INCLUDE_PATH /usr/include/gdal
-
-# Install Chrome WebDriver
-RUN CHROMEDRIVER_VERSION="78.0.3904.105" && \
-    mkdir -p /opt/chromedriver-$CHROMEDRIVER_VERSION && \
-    curl -sS -o /tmp/chromedriver_linux64.zip http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip && \
-    unzip -qq /tmp/chromedriver_linux64.zip -d /opt/chromedriver-$CHROMEDRIVER_VERSION && \
-    rm /tmp/chromedriver_linux64.zip && \
-    chmod +x /opt/chromedriver-$CHROMEDRIVER_VERSION/chromedriver && \
-    ln -fs /opt/chromedriver-$CHROMEDRIVER_VERSION/chromedriver /usr/local/bin/chromedriver
-
 RUN mkdir /tfm_uoc_crawling_system
 
 ADD . /tfm_uoc_crawling_system/
 
-# Authorize SSH Host
-RUN mkdir -p /root/.ssh && \
-    chmod 0700 /root/.ssh && \
-    ssh-keyscan github.com > /root/.ssh/known_hosts
+RUN pip install Cython django-haystack
 
-# Add the keys and set permissions
-RUN echo "$ssh_prv_key" > /root/.ssh/id_rsa && \
-    echo "$ssh_pub_key" > /root/.ssh/id_rsa.pub && \
-    chmod 600 /root/.ssh/id_rsa && \
-    chmod 600 /root/.ssh/id_rsa.pub
-
-RUN cd /tfm_uoc_crawling_system && pip install -r requirements_docs.txt || echo "ignore error"
-RUN cd /tfm_uoc_crawling_system && python setup.py develop
-RUN cd /tfm_uoc_crawling_system && pip install -r requirements.txt || echo "ignore error"
-RUN cd /tfm_uoc_crawling_system && pip install -r requirements.base.txt || echo "ignore error"
-RUN cd /tfm_uoc_crawling_system && pip install -r requirements_tests.txt || echo "ignore error"
-RUN cd /tfm_uoc_crawling_system && pip install -r requirements_test.base.txt || echo "ignore error"
+RUN cd /tfm_uoc_crawling_system \
+    && python setup.py develop \
+    && pip install django_caravaggio_rest_api[spatial] \
+    && pip install -r requirements_test.base.txt || echo "ignore error"
 
 RUN mkdir -p /data/tfm_uoc_crawling_system/log
 
